### ISSUE TITLE
Do you want information about modifying a custody and parenting plan or child support order from an Alaska case :
User: other feedback

### ISSUE THREAD

**Issue by AKDocAssemble** [A2JatAKCourts/docassemble-ChangingChildCustodyIssues#2]
## How helpful was this form?
Choices are "very helpful", "somewhat helpful", "not helpful at all".
None
## User feedback:  
> There may be a problem with this question.
If answer Yes -get asked about standing order - if no, interview breaks. 
Order is only set now by testing accordion steps so this may resolve.
Also right now, even if user says they want to change an out of state order, they get asked this question.  shouldn't get this. But may be due to accordion step testing errrors.

Question id: `Do you want information about modifying a custody and parenting plan or child support order from an Alaska case`

Variable being sought: `modify_within_15_days`

**Comment by CaroRob** [comment]
No longer a problem - not getting asked about standing order any more.
