### ISSUE TITLE
interim order date question :
User: other feedback

### ISSUE THREAD

**Issue by AKDocAssemble** [A2JatAKCourts/docassemble-ChangingChildCustodyIssues#3]
## How helpful was this form?
Choices are "very helpful", "somewhat helpful", "not helpful at all".
None
## User feedback:  
> fix required date in date field in this question

Question id: `interim order date question`

Variable being sought: `interim_order_date`

**Comment by CaroRob** [comment]
Fixed I think I cannot find a problem
